// export default [
//   {
//     id: null,
//     title: "From Ferraris to Fries: A Thrilling Summer Escape!",
//     desc: "This summer, my friends and I took an unforgettable road trip to Stoney Creek near Niagara Falls. We celebrated two birthdays in style, driving 6 exotic cars like a Ferrari, Lamborghini, and Porsche 911 Turbo at Ultimate Exotics. After a thrilling day on the road, we wrapped it up by the water with a mouthwatering burger and fries—a perfect ending to an epic adventure.",
//     img: JSON.stringify({ filename: "1733237869577_travel - cars.png" }), 
//     date: "2024-06-15 14:30:00",
//     uid: 1,
//     cat: "travel",
//   },
//   {
//     id: null,
//     title: "Swinging into Sweetness: Golf, Cake & Connection",
//     desc: "This year, I picked up golf, and wow—what a game-changer! Not only have I improved my swing (kind of), but I’ve also reconnected with old friends, met amazing new people, and even brought in fresh business opportunities. To celebrate, I made a homemade birthday cake decked out with golf-themed decorations—a sweet tribute to the sport that’s brought so much fun and connection into my life. Next on my bucket list? Golf travel! Scotland, Florida, Japan—watch out, here I come (eventually). Until then, it’s swings, sweet treats, and making memories on the green.",
//     img: JSON.stringify({ filename: "1733237869577_travel - cars.png" }),
//     date: "2024-07-22 11:45:00",
//     uid: 1,
//     cat: "travel",
//   },
//   {
//     id: null,
//     title: "Wings, Fries, and Family Ties: A Road Trip to Remember",
//     desc: "This road trip wasn’t just about the miles—it was about reconnecting. My partner, his dad, and I hit the road to Buffalo for some legendary Duff’s wings and fries (totally worth it) and then headed to Baltimore to meet extended family for the first time. It was bittersweet—spending time with loved ones who are getting older and soaking up moments that truly matter. Staying in a quiet suburban house surrounded by greenery made it even more special. No endless scrolling, just laughs, stories, and a lot of heart. Sometimes, all it takes is good food, great company, and a little disconnect to feel truly connected.",
//     img: JSON.stringify({ filename: "1733237878426_travel - wings buffalo.png" }),
//     date: "2024-08-10 18:20:00",
//     uid: 1,
//     cat: "travel",
//   },
//   {
//     id: null,
//     title: "Salmon Nights: Cooking Healthy, Saving Big",
//     desc: "<p>Cooking at home hits all the right notes: it’s budget-friendly, healthier, and lets me get creative. My latest creation? </p><p><br></p><p>Baked salmon with coleslaw—a brain-boosting, skin-loving combo.</p><p><br></p><p>Did you know salmon is packed with omega-3 fatty acids, which can improve memory and keep your skin glowing? It’s also loaded with protein, vitamin D, and antioxidants to keep you feeling your best.</p><p><br></p><p>Even though salmon isn’t my favorite protein, I can’t deny how good it is for the body (and the wallet). Plus, when paired with crunchy, tangy coleslaw, it’s a win-win on the plate!</p><p><br></p><p>What’s your favorite healthy dish to whip up at home? Let me know!</p>",
//     img: JSON.stringify({ filename: "1733237815480_food - salmon.png" }),
//     date: "2024-09-05 21:00:00",
//     uid: 1,
//     cat: "food",
//   },
//   {
//     id: null,
//     title: "'Hole-in-One Cravings: Shawarma Poutine Bliss",
//     desc: "Cooking at home hits all the right notes: it’s budget-friendly, healthier, and lets me get creative. My latest creation? Baked salmon with coleslaw—a brain-boosting, skin-loving combo. Did you know salmon is packed with omega-3 fatty acids, which can improve memory and keep your skin glowing? It’s also loaded with protein, vitamin D, and antioxidants to keep you feeling your best. Even though salmon isn’t my favorite protein, I can’t deny how good it is for the body (and the wallet). Plus, when paired with crunchy, tangy coleslaw, it’s a win-win on the plate! What’s your favorite healthy dish to whip up at home? Let me know!",
//     img: JSON.stringify({ filename: "1733237841867_food -shawarma.png" }),
//     date: "2024-10-12 16:35:00",
//     uid: 1,
//     cat: "food",
//   },
//   {
//     id: null,
//     title: "Caviar, Oysters & Vibes: Ryu Izakaya Magic",
//     desc: "Ryu Izakaya in Richmond Hill is a feast for the senses. With its dragon mural, cherry blossom tree, and a DJ after 9 PM, it’s more than just dinner—it’s an experience. I’m not a fan of caviar, but the artfully plated oysters and caviar were too stunning not to capture. This spot is perfect for foodies who love great vibes and picture-perfect dishes. What’s your favourite spot for food and ambiance?",
//     img: JSON.stringify({ filename: "1733237789212_art - caviar.png" }),
//     date: "2024-11-01 20:15:00",
//     uid: 1,
//     cat: "art",
//   },
//   {
//     id: null,
//     title: "Ramen, Cappuccinos & Chill Vibes at Chillax",
//     desc: "Chillax in Richmond Hill, Ontario is my go-to spot for a quick, quality bite. Their ramen is delicious, their cappuccinos are pure art, and the cozy atmosphere is always inviting. I love how efficient they are—you can check in and order through an app, but they’re just as happy to take your order in person. Plus, the cute plushies and gifts for sale make it even more charming. Great food, great vibes, and great service—Chillax always delivers. What’s your favorite local spot to unwind?",
//     img: JSON.stringify({ filename: "1733237802560_art - ramen.png" }),
//     date: "2024-11-03 14:45:00",
//     uid: 1,
//     cat: "art",
//   },
//   {
//     id: null,
//     title: "Sushi, Style & Sweet Gestures",
//     desc: "There’s something special about sushi delivered with love—especially when it’s wrapped in a beautifully designed cloth. A close friend surprised me with this gorgeous sushi box, and the quality was just as amazing as the presentation. The floral cloth beneath the box made it feel extra thoughtful and unique, turning an already delicious treat into something unforgettable. Good food, great friends, and those little touches that make life sweeter—this delivery was a win all around! What’s the most thoughtful food gift you’ve ever received?",
//     img: JSON.stringify({ filename: "1733237810328_art - sushi.png" }),
//     date: "2024-11-07 12:30:00",
//     uid: 1,
//     cat: "art",
//   },
//   {
//     id: null,
//     title: "Pizza, Games, and a Victory Lap",
//     desc: "There’s nothing like homemade pizza, especially when it’s made by a friend who’s all about fresh ingredients and new tech. He crafted everything from scratch, using his cool new pizza oven to create perfect pies for our get-together. The night was a blend of delicious food and friendly competition. After indulging in those amazing pizzas, we battled it out in FIFA—and guess what? I took the win...",
//     img: JSON.stringify({ filename: "1733237856326_technology - pizza.png" }),
//     date: "2024-11-10 19:55:00",
//     uid: 1,
//     cat: "technology",
//   },
// //Sophia's
// {
//   id: null,
//   title: "Cheers to the Graduates",
//   desc: "Celebrating the end of an incredible journey! As a Teaching Assistant for the Software Engineering program at BrainStation, I've had the chance to learn, grow, and support so many talented students eager to break into the tech world. This week marks the finish line, and I just want to say: Congratulations to everyone graduating! You did it, and I’m so proud of all your hard work. Here’s to new beginnings and amazing opportunities ahead! What’s next on your tech journey?",
//   date: "2024-11-15 12:55:00",
//   uid: 2, 
//   cat: "technology",
// },
// ];
